// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2) {
  return window['go']['main']['App']['AddTask'](arg1, arg2);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ClearFinished() {
  return window['go']['main']['App']['ClearFinished']();
}

export function FfmpegVersion() {
  return window['go']['main']['App']['FfmpegVersion']();
}

export function GetLocale() {
  return window['go']['main']['App']['GetLocale']();
}

export function ListEncoders() {
  return window['go']['main']['App']['ListEncoders']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFiles(arg1) {
  return window['go']['main']['App']['PickFiles'](arg1);
}

export function ProbeMediaInfo(arg1) {
  return window['go']['main']['App']['ProbeMediaInfo'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadAudioTags(arg1) {
  return window['go']['main']['App']['ReadAudioTags'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function WriteAudioTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteAudioTags'](arg1, arg2, arg3);
}
