// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string,arg2:main.ConvertOptions):Promise<main.ConvertTask>;

export function CancelTask(arg1:string):Promise<boolean>;

export function ClearFinished():Promise<void>;

export function FfmpegVersion():Promise<string>;

export function GetLocale():Promise<string>;

export function ListEncoders():Promise<Array<string>>;

export function ListTasks():Promise<Array<main.ConvertTask>>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenInFolder(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PickFiles(arg1:Array<Record<string, any>>):Promise<Array<string>>;

export function ProbeMediaInfo(arg1:string):Promise<main.MediaInfo>;

export function QuitApp():Promise<void>;

export function ReadAudioTags(arg1:string):Promise<main.AudioTags>;

export function RetryTask(arg1:string):Promise<boolean>;

export function SetLocale(arg1:string):Promise<boolean>;

export function WriteAudioTags(arg1:string,arg2:main.AudioTags,arg3:string):Promise<boolean>;
